services:
  fsm_lidar_odometry:

    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: li9i/fsm-lidar-odometry:lyrical
    container_name: fsm_lidar_odometry
    tty: true
    network_mode: "host"
    ipc: host
